apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-metrics-ingress
  namespace: monitoring
spec:
  ingressClassName: "nginx"
  rules:
    - host: custom-metrics.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: custom-metrics-service
                port:
                  number: 80
