apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: custom-metrics-rollout
  namespace: monitoring
  labels:
    app: custom-metrics
spec:
  replicas: 2
  strategy:
    canary:
      canaryService: custom-metrics-service-canary
      stableService: custom-metrics-service
      trafficRouting:
        nginx:
          stableIngress: custom-metrics-ingress
      steps:
        - setWeight: 10
        - pause: { duration: 20s }
        - setWeight: 50
        - pause: { duration: 20s }
        - setWeight: 100
  selector:
    matchLabels:
      app: custom-metrics
  template:
    metadata:
      labels:
        app: custom-metrics
    spec:
      containers:
        - name: custom-metrics
          image: ahmedsayedtalib/custommetrics:6
          ports:
            - containerPort: 8000
