apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-service-canary
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: custom-metrics
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

